### ISSUE TITLE
Feature request: Add "ignore names" field from main config under search field (similar to VCS)

### ISSUE THREAD

**Issue by orjanb-ne** [jonathan-dejong/find-and-replace-with-prev#2]
![codebasics_searchadvanced](https://cloud.githubusercontent.com/assets/22000464/26156018/40de7d84-3b15-11e7-9e01-65083605175d.png)

**Comment by jonathan-dejong** [comment]
Hi @orjanb-ne 

I wont be doing any extra work on this package. I have made a PR to the original core package and my hopes is that he will merge it into core :)
